import pandas as pd
import os
configfile: "config/config.yaml"
import snparcher_utils

samples = snparcher_utils.parse_sample_sheet(config)
BIOSAMPLE = samples["BioSample"].unique().tolist()
REFGENOME = samples['refGenome'].unique().tolist()
FINAL_PREFIX = config["final_prefix"]

rule all:
    input:
        expand("results/{refGenome}/paralogs/{prefix}.paralogs.bed", refGenome=REFGENOME, prefix=FINAL_PREFIX),
        expand("results/{refGenome}/paralogs/{prefix}.paralogs.png", refGenome=REFGENOME, prefix=FINAL_PREFIX)

rule get_bam_list:
    """
    List of all bam files
    """
    input:
        bams = expand("results/{refGenome}/bams/{sample}_final.bam", refGenome=REFGENOME, sample=BIOSAMPLE)
        bam_list = temp("results/{refGenome}/paralogs/{prefix}.bam_list.txt")
    log:
        "logs/{refGenome}/paralogs/{prefix}.log"
    shell:
        """
        printf "%s\n" {input.bams} > {output.bam_list}
        """

rule get_snps_list:
    """
    List of all snp positions
    """
    input:
        vcf = "results/{refGenome}/{prefix}_raw.vcf.gz"
    output:
        snps_list = temp("results/{refGenome}/paralogs/{prefix}_raw.snps_list.bed")
    conda:
        "envs/paralogs.yml"
    shell:
        """
        bcftools view --no-header {input.vcf} | \
            awk -F '\t' '{{print $1 "\t" $2}}' > {output.snps_list}
        """

rule ngs_paralog:
    """
    Main ngsparalog command
    """
    input:
        bam_list = "results/{refGenome}/paralogs/{prefix}.bam_list.txt",
        snps_list = "results/{refGenome}/paralogs/{prefix}_raw.snps_list.bed",
        ngs_paralogs_path = config["ngs_paralogs_path"]
    output:
        paralogs_lr = "results/{refGenome}/paralogs/{prefix}.lr"
    conda:
        "envs/paralogs.yml"
    log:
        "logs/{refGenome}/paralogs/{prefix}.log"
    params:
        minQ = config["minQ"],
        minind = config["minind"],
        mincov = config["mincov"]
    shell:
        """
        samtools mpileup -b {input.bam_list} -l {input.snps_list} -q 0 -Q 0--ff UNMAP,DUP -d 0| \
	        ngsParalog calcLR -infile - \
                -outfile {output.paralogs_lr} \
                -minQ {params.minQ} \
                -minind {params.minind} \
                -mincov {params.mincov}
        """

rule chi2:
    """
    Chi2 test for each site
    """
    input:
        paralogs_lr = "results/{refGenome}/paralogs/{prefix}.lr"
    output:
        paralogs_pval = "results/{refGenome}/paralogs/{prefix}.pval.tsv"
    conda:
        "envs/paralogs.yml"
    shell:
        """
        python3 "scripts/get_paralogs.py" \
	        -i {input.paralogs_lr} \
	        -o {output.paralogs_pval} --pval
        """

rule get_paralogs:
    """
    Mark sites below 0.05 as sites belonging to a paralogous region
    """
    input:
        paralogs_pval = "results/{refGenome}/paralogs/{prefix}.pval.tsv"
    output:
        paralogs = "results/{refGenome}/paralogs/{prefix}.paralogs.bed"
    conda:
        "envs/paralogs.yml"
    shell:
        """
        python3 "scripts/get_paralogs.py" \
	        -i {input.paralogs_pval} \
	        -o {output.paralogs} --save
        """

# Maybe better to do it outside ?
rule plot_paralogs:
    """
    Draw Manhattan plot
    """
    input:
        paralogs_pval = "results/{refGenome}/paralogs/{prefix}.pval.tsv"
    output:
        paralogs_plot = "results/{refGenome}/paralogs/{prefix}.paralogs.png"
    conda:
        "envs/paralogs.yml"
    shell:
        """
        python3 "scripts/get_paralogs.py" \
	        -i {input.paralogs_pval} \
	        -o {output.paralogs_plot} --plot
        """